### ISSUE TITLE
Add license file

### ISSUE THREAD

**Issue by tbeu** [fnoyanisi/zString#3]
* Add a license file to the repo
* zstring_remove_chr.h seems to have Original BSD 4-Clause license wheras all others are Simplified BSD 2-Clause.

**Comment by fnoyanisi** [comment]
Updated license for zstring_remove_chr() and added a LICENSE file.
Changes have been committed as version 1.8.1

Thanks!

**Comment by tbeu** [comment]
It seems like GitHub web interface does not detect the custom header lines of the LICENSE file in the repo root. It does for example in https://github.com/tbeu/ExternData.
