### ISSUE TITLE
Thread-safe strtok variants

### ISSUE THREAD

**Issue by tbeu** [fnoyanisi/zString#4]
Thread-safe variants of both strtok implementations (that do not rely on static variables) are interesting. See strtok_r (on POSIX) or strtok_s (the Win-specific one with three arguments) for maintaining the context between successive calls.

**Comment by fnoyanisi** [comment]
In fact, there is also strsep() function, which handles empty fields and is thread safe but not portable (many systems must have it though)

https://www.freebsd.org/cgi/man.cgi?query=strsep&manpath=FreeBSD+11.0-RELEASE

And here is the implementation on FreeBSD
https://svnweb.freebsd.org/base/head/lib/libc/string/strsep.c?view=markup

Thanks!

**Comment by tbeu** [comment]
See https://github.com/tbeu/ExternData/blob/master/ExternData/Resources/C-Sources/zstring_strtok_dquotes.h for my modifications.
