### ISSUE TITLE
Type for pointer difference

### ISSUE THREAD

**Issue by tbeu** [fnoyanisi/zString#5]
I guess in the trim functions, variable `index` should be of type `ptrdiff_t` and not `int`.

**Comment by fnoyanisi** [comment]
Hi there,
In zString, I tried to avoid using any library functions and headers (for exmaple, although not 100% the same but, zstring_search_chr() could well be replaced by strchr() [1] library function). 

ptrdiff_t is the right type for the index variable, but do you think, given that if we do not include stddef.h, "long" would be a better fit than int?

[1] https://www.freebsd.org/cgi/man.cgi?query=strchr&sektion=3

**Comment by tbeu** [comment]
Types long and int are same size on MSVC. Thus there will be no benfit there. You still can make it unsigned int, if you do not want to include stddef.h.

**Comment by fnoyanisi** [comment]
FreeBSD (clang) has it defined, depending on the architecture, 64bit int (aka long long) or 32bit int. I will change the type of "index" from "int" to "unsigned long".

Thanks
